"""Production C02 connected primary-actor macro affiliation.

The package owns one fixed 40-km categorical torus and construction
certificates.  It deliberately makes no contact-regime, kinematics, geology,
elevation, water, coast, land, delivered-window, or map claim.
"""

from ._util import FabricFormationError, FabricRecordError
from .audit import (
    FabricAuditResult,
    audit_bundle_record,
    run_cohort_audits,
    run_fabric_audits,
)
from .cache import (
    FabricCacheKeys,
    changed_fabric_cache_keys,
    compute_fabric_cache_keys,
)
from .cohort import (
    CohortReceipt,
    DevelopmentFabricCohort,
    DevelopmentFabricMember,
    FormationFailureRecord,
    build_development_fabric_cohort,
    validation_guard_is_closed,
)
from .constants import (
    ATTEMPT_ID,
    CASE_ID,
    COMPARISON_FAMILY_ID,
    DISPLAY_LABEL,
    EVIDENCE_KIND,
    ROADMAP_RUN,
    STAGE_ID,
    STAGE_VERSION,
)
from .construction import (
    build_tectonic_fabric_state,
    toroidal_squared_distance_m2,
)
from .context import (
    FabricFormationContext,
    FabricIsolationError,
    build_fabric_context,
    build_fabric_context_with_poison_audit,
)
from .diversity import (
    FabricDiversityReport,
    PairwiseDiversity,
    adjusted_rand_similarity,
    adjusted_rand_similarity_from_table,
    build_diversity_report,
    canonical_partition_bytes,
    canonical_partition_fingerprint,
    contingency_table,
    optimal_label_agreement,
    optimal_label_agreement_from_table,
)
from .growth import (
    GrowthResult,
    clear_growth_caches,
    derive_resistance_controls,
    grow_affiliation,
    resistance_array,
)
from .layout import (
    build_primary_actor_layout,
    derive_layout_controls,
    local_coordinates,
    multiply_high_axis,
    signed_periodic_delta,
    triangle_wave,
)
from .metrics import (
    ActorMorphologyMetrics,
    FabricCensusMetrics,
    FabricMorphologyMetrics,
    measure_census,
    measure_morphology,
)
from .observation import (
    CanonicalAffiliationObservation,
    FabricObservation,
    observe_analysis,
    observe_canonical_affiliation,
    observe_grid,
    observe_parent_census,
)
from .records import (
    ActorArrivalSummary,
    ArrivalSummaryRecord,
    GrowthCertificate,
    LayoutControlRecord,
    PrimaryActorRecord,
    ResistanceControlRecord,
    TectonicFabricSpec,
    TectonicFabricState,
    actor_lineage_id,
    actor_state_id,
    frozen_c02_spec,
    frozen_c5_spec,
)
from .topology import (
    STABILITY_OFFSETS_M,
    canonical_cell_indices,
    canonical_flat_index,
    endpoint_agreement_count,
    evaluate_slots_and_stability,
    owner_slot,
    owner_slots,
    strict_all_eight,
)


__all__ = [
    "ATTEMPT_ID",
    "ActorArrivalSummary",
    "ActorMorphologyMetrics",
    "ArrivalSummaryRecord",
    "CASE_ID",
    "COMPARISON_FAMILY_ID",
    "CanonicalAffiliationObservation",
    "CohortReceipt",
    "DISPLAY_LABEL",
    "DevelopmentFabricCohort",
    "DevelopmentFabricMember",
    "EVIDENCE_KIND",
    "FabricAuditResult",
    "FabricCacheKeys",
    "FabricCensusMetrics",
    "FabricDiversityReport",
    "FabricFormationContext",
    "FabricFormationError",
    "FabricIsolationError",
    "FabricMorphologyMetrics",
    "FabricObservation",
    "FabricRecordError",
    "FormationFailureRecord",
    "GrowthCertificate",
    "GrowthResult",
    "LayoutControlRecord",
    "PairwiseDiversity",
    "PrimaryActorRecord",
    "ResistanceControlRecord",
    "ROADMAP_RUN",
    "STABILITY_OFFSETS_M",
    "STAGE_ID",
    "STAGE_VERSION",
    "TectonicFabricSpec",
    "TectonicFabricState",
    "actor_lineage_id",
    "actor_state_id",
    "adjusted_rand_similarity",
    "adjusted_rand_similarity_from_table",
    "audit_bundle_record",
    "build_development_fabric_cohort",
    "build_diversity_report",
    "build_fabric_context",
    "build_fabric_context_with_poison_audit",
    "build_primary_actor_layout",
    "build_tectonic_fabric_state",
    "canonical_cell_indices",
    "canonical_flat_index",
    "canonical_partition_bytes",
    "canonical_partition_fingerprint",
    "changed_fabric_cache_keys",
    "clear_growth_caches",
    "compute_fabric_cache_keys",
    "contingency_table",
    "derive_layout_controls",
    "derive_resistance_controls",
    "endpoint_agreement_count",
    "evaluate_slots_and_stability",
    "frozen_c02_spec",
    "frozen_c5_spec",
    "grow_affiliation",
    "local_coordinates",
    "measure_census",
    "measure_morphology",
    "multiply_high_axis",
    "observe_analysis",
    "observe_canonical_affiliation",
    "observe_grid",
    "observe_parent_census",
    "optimal_label_agreement",
    "optimal_label_agreement_from_table",
    "owner_slot",
    "owner_slots",
    "resistance_array",
    "run_cohort_audits",
    "run_fabric_audits",
    "signed_periodic_delta",
    "strict_all_eight",
    "toroidal_squared_distance_m2",
    "triangle_wave",
    "validation_guard_is_closed",
]
